name: Update Credly Badges

on:
  schedule:
    - cron: "0 2 * * *"   # Jalan otomatis tiap hari jam 02:00 UTC
  workflow_dispatch:        # Bisa juga dijalankan manual dari tab Actions

permissions:
  contents: write           # Izin untuk edit README.md

jobs:
  update-readme:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: sandi-r
